table UNIQUE_CARRIERS
	lineageTag: 9f673ed6-3fb5-4718-a927-985997be373e

	column Code
		dataType: string
		lineageTag: 1c000ddd-8fd4-4e5d-a5c2-4c9e078eb261
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	column Airline
		dataType: string
		lineageTag: 45bee814-2d54-4de2-98dd-3c3e94fb6918
		summarizeBy: none
		sourceColumn: Airline

		annotation SummarizationSetBy = Automatic

	partition UNIQUE_CARRIERS = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\Trainee\Downloads\UNIQUE_CARRIERS (1).csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(Quelle,{{"Column1", type text}, {"Column2", type text}}),
				    #"Umbenannte Spalten" = Table.RenameColumns(#"Geänderter Typ",{{"Column1", "Code"}, {"Column2", "UNIQUE_CARRIERS"}}),
				    #"Geänderter Typ1" = Table.TransformColumnTypes(#"Umbenannte Spalten",{{"Code", type text}}),
				    #"Höher gestufte Header" = Table.PromoteHeaders(#"Geänderter Typ1", [PromoteAllScalars=true]),
				    #"Geänderter Typ2" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Code", type text}, {"Description", type text}}),
				    #"Umbenannte Spalten1" = Table.RenameColumns(#"Geänderter Typ2",{{"Description", "Airline"}})
				in
				    #"Umbenannte Spalten1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

