table MP_Sediment
	lineageTag: ebcb48ae-43e6-4d33-acab-14b7f195b66f

	column Objekt
		dataType: string
		lineageTag: 6fa581c9-f101-4129-bf5b-59b164695a3d
		summarizeBy: none
		sourceColumn: Objekt

		annotation SummarizationSetBy = Automatic

	column Breitengrad
		dataType: double
		lineageTag: 70423e95-5eea-4954-8f89-56f58c59e808
		summarizeBy: sum
		sourceColumn: Breitengrad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Längengrad
		dataType: double
		lineageTag: 28d7ea5c-0179-48ca-8907-f95bb9388e4d
		summarizeBy: sum
		sourceColumn: Längengrad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ozean
		dataType: string
		lineageTag: f355644e-1398-40a1-b278-ba5688a2cb09
		summarizeBy: none
		sourceColumn: Ozean

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f8830236-dfe8-4e2a-b500-ead9813e6bf1
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Meeresumgebung
		dataType: string
		lineageTag: f048da24-8c73-4a7e-8e41-7335186516d0
		summarizeBy: none
		sourceColumn: Meeresumgebung

		annotation SummarizationSetBy = Automatic

	column 'Mikroplastik Menge'
		dataType: double
		lineageTag: f07432a2-2185-4e56-8db0-6ef52b514e46
		summarizeBy: sum
		sourceColumn: Mikroplastik Menge

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Einheit
		dataType: string
		lineageTag: 94666b25-0d34-4189-a756-2eb533af25a7
		summarizeBy: none
		sourceColumn: Einheit

		annotation SummarizationSetBy = Automatic

	column 'Konzentration Range'
		dataType: string
		lineageTag: ace54f55-d68f-42c7-acbe-3a1d23c018bc
		summarizeBy: none
		sourceColumn: Konzentration Range

		annotation SummarizationSetBy = Automatic

	column 'Konzentration Klasse'
		dataType: string
		lineageTag: 2690b890-0ad2-42f4-ab12-f6bfafe6887e
		summarizeBy: none
		sourceColumn: Konzentration Klasse

		annotation SummarizationSetBy = Automatic

	column Datum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 21c79201-db37-45f4-96be-b66faf6b35d2
		summarizeBy: none
		sourceColumn: Datum

		variation Variation
			isDefault
			relationship: 64f448d9-f979-462c-8ff0-08718d9039da
			defaultHierarchy: LocalDateTable_cd66ec92-f111-45d1-bbfc-d4fee2cc474f.Datumshierarchie

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Jahr
		dataType: int64
		formatString: 0
		lineageTag: 6d41f3ba-f7fe-491a-91c4-e9de5e4566e5
		summarizeBy: sum
		sourceColumn: Jahr

		annotation SummarizationSetBy = Automatic

	column Monat
		dataType: int64
		formatString: 0
		lineageTag: 68aad6d2-fd73-43c3-be31-7b79b922c2c2
		summarizeBy: sum
		sourceColumn: Monat

		annotation SummarizationSetBy = Automatic

	column 'Breitengrad dez'
		dataType: double
		lineageTag: c8e990b8-da5b-4f61-959d-555c0519cc03
		summarizeBy: sum
		sourceColumn: Breitengrad dez

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Längengrad dez'
		dataType: double
		lineageTag: 66f89410-9d1a-42c6-ae69-9ced9bbe58ba
		summarizeBy: sum
		sourceColumn: Längengrad dez

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition MP_Sediment = m
		mode: import
		source =
				let
				    Quelle = Marine_Microplastics_NOAA,
				    OceanSediment = Table.SelectRows(Quelle, each ([Meeresumgebung] = "Ocean sediment")),
				    #"Entfernte Spalten" = Table.RemoveColumns(OceanSediment,{"Water Sample Depth (m)", "Sampling Method", "Mesh Size (mm)", "Short Reference", "Long Reference", "DOI", "Organization", "Keywords", "NCEI Accession Number", "NCEI Accession Link", "Symbology", "GlobalID", "x", "y"})
				in
				    #"Entfernte Spalten"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

